title: less
#email: no.spam@example.com
description:
baseurl:
url: https://epi.github.io
twitter_username: C012294
github_username:  epi
disqus:
  shortname: epi-github-io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
