title: less
#email: no.spam@example.com
description: > # this means to ignore newlines until "baseurl:"
  Random rants on programming, mostly in dlang.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: C012294
github_username:  epi
disqus:
  shortname: epi-github-io

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
